### ISSUE TITLE
Update "date_now" function to handle bad arguments

### ISSUE THREAD

**Issue by fhightower** [democritus-project/d8s-dates#15]
HELP WANTED 👋  : If you'd like to take this challenge on, please let me know! Even if you're new to Python and/or github, this is a great place to start and I'd be happy to help walk you through this challenge as much as you need - don't hesitate to ask.

This particular issue will give you some exposure to raising exceptions based on the keyword arguments given to a function.

---

The [`date_now`](https://github.com/democritus-project/democritus-dates/blob/main/democritus_dates/dates_and_times.py#L97) function, takes two, keyword arguments:

- `convert_to_current_timezone`
- `utc`

If they are both True, the function should raise an exception because it isn't clear what the user wants to do (should we make the date timezone aware based on the current timezone or UTC?). Please update the `date_now` function to raise an error if both `convert_to_current_timezone` and `utc` are `True`.

**Comment by waleedwasfy96** [comment]
Hi @fhightower , I would like to take this on but I'm new to the github contribution process and would appreciate it if you can walk me through the process.

**Comment by fhightower** [comment]
Wonderful 🎉  ! Thanks for wanting to be involved and for asking @waleedwasfy96!

## Process

Here is the process from a high level:

0. Claim the task/issue you want to work on
    - This is already done! I've assigned this issue to you and we'll close it when you're done.
1. [Fork][fork] this repository
2. [Clone][clone] the forked repository locally
3. [Create a branch][branch]
    - I recommend giving your branch a helpful name like `git checkout -b update-date-now-arg-handling` or something like that
4. Make your code changes
    - This is where you actually modify and improve the code
5. Push your changes to your fork
6. [Create a pull request][pr] from your fork to this repository
7. We'll review the updates you made and merge the PR!

## Guides

Three guides that walk through each step (or most steps) in this process are:

- https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project
- https://training.galaxyproject.org/training-material/topics/contributing/tutorials/github-command-line-contribution/tutorial.html
- https://guides.github.com/activities/forking/

## Questions? Please Ask!

If you have any follow-up questions, don't hesitate to ask! It takes some practice to get the hang of contributing.

[fork]: https://docs.github.com/en/github/getting-started-with-github/fork-a-repo
[clone]: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository
[branch]: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
[pr]: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork
