### ISSUE TITLE
Write `time_as_float` function to convert a time to a float (e.g. 12:30 -> 12.5)

### ISSUE THREAD

**Issue by fhightower** [democritus-project/d8s-dates#7]
HELP WANTED: If you'd like to take this challenge on, please let me know! Even if you're new to Python and/or github, this is a great place to start and I'd be happy to help walk you through this challenge as much as you need - don't hesitate to ask.

---

# Description

It would be helpful to have a function to convert a time (e.g. 12:30) to a float (e.g. 12.5) where the value after the decimal point represents the percent of the hour that has gone by.

# Examples

Input | Output
------ | ------
12:00 | 12.0
12:10 | 12.1666...7
12:15 | 12.25
12:30 | 12.5
12:45 | 12.75

# Suggested Function Signature

I imagine the function signature being:

```python
def time_as_float(time_string: str) -> float:
    ...
```

If you have any thoughts or suggestions, I'm open to input.

**Comment by jdb9597** [comment]
Hi! Can I take this on? I'm still relatively new to using GitHub but I know some basic Python.

**Comment by fhightower** [comment]
~Hi @jdb9597! Thanks for helping out and for the PRs! I should be able to review those tonight or tomorrow and get them merged.~ 

Update: @jdb9597 - Thanks for asking and for wanting to get involved! Unfortunately, there are already a couple of pull requests addressing this issue (sorry about that)...

BUT... I hope to have more issues added to the Democritus Project soon, so please check back later!

**Comment by fhightower** [comment]
This was completed by @VcelistMC in #8 .
